os:
  - linux
  - osx
language: rust
rust:
  - nightly
sudo: false
branches:
  only:
      - master
install:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium_ffi.sh | source
  - echo $LD_LIBRARY_PATH
  - echo $PKG_CONFIG_PATH
script:
  - cargo build --verbose --features "use-mock-routing"
  - cargo test --verbose --features "use-mock-routing"
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/deploy_gh-pages.sh | bash
env:
  global:
    secure: "Q+SwRzZ0meFuwNj8DDctw6Wwk50/GhG9gQJQMyIcT0vdcVGeQlBSscQT9z2LHcezpS4hIgyosEqteOAtOmT78Lxaq0PVLX84lcym4WO8Bk7OQZ5jHddImCvygVAByZwEMC2MHyKkBkfsijAz0qvyyFIuPMbZ+I69jGppOtU/GB0="
