[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "SAFE API - FFI library"
documentation = "http://maidsafe.github.io/safe_ffi/latest/"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "safe_ffi"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_ffi"
version = "0.2.0"

[dependencies]
libc = "~0.2.4"
maidsafe_utilities = "~0.1.5"
routing = "~0.5.2"
safe_core = "~0.4.0"
safe_dns = "~0.4.0"
safe_nfs = "~0.4.0"
sodiumoxide = "~0.0.9"

[features]
use-mock-routing = ["safe_dns/use-mock-routing", "safe_nfs/use-mock-routing", "safe_core/use-mock-routing"]

[lib]
crate_type = ["staticlib", "dylib", "rlib"]
name = "safe_ffi"
